export enum Categories {
  ADMINISTRATION_MANAGEMENT = 1,
  SALES = 2,
  FINANCE_STATISTICS = 3,
  PR_MARKETING = 4,
  LOGISTICS_TRANSPORT_DISTRIBUTION = 5,
  IT_PROGRAMMING = 6,
  LEGAL = 7,
  MEDICINE_PHARMACY = 8,
  OTHER = 9,
  FOOD = 10,
  CONSTRUCTION_REPAIR = 11,
  EDUCATION = 12,
  MEDIA_PUBLISHING = 13,
  BEAUTY_FASHION = 14,
  CLEANING = 16,
  SECURITY = 17,
  TECHNICAL_PERSONNEL = 18
}
